global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "hooktrace-api"
    static_configs:
      - targets: ["api:3001"]

  - job_name: "hooktrace-worker"
    static_configs:
      - targets: ["worker:8001"]